# .github/workflows/azure-function-deploy.yml
name: Test and Deploy Azure Function

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/functions/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest src/tests --maxfail=1 --disable-warnings -q

      - name: Zip function app contents
        run: |
          cd src/functions
          zip -r ../../functionapp.zip *

      - name: Upload function app zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-zip
          path: functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.event_name == 'push'

    steps:
      - name: Download function app zip artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp-zip
          path: .

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
            --src functionapp.zip
